core/urls.py
from django.urls import path
from . import views
from .views import ProfileView
from django.conf import settings
from django.conf.urls.static import static

app_name = 'core'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('profile/', ProfileView.as_view(), name='profile'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

matching/urls.py
from django.urls import path
from . import views

app_name = 'matching'

urlpatterns = [
    path('search_pair/', views.SearchPairListView.as_view(), name='search_pair'),
    path('like/<int:user_id>/', views.LikeUserView.as_view(), name='like'),
    path('dislike/<int:user_id>/', views.DislikeUserView.as_view(), name='dislike'),
]

project_laska/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
    path('stories/', include('stories.urls')),
    path('matching/', include('matching.urls')),
    path('messages/', include('messaging.urls', namespace='messaging')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Group, Permission


class User(AbstractUser):
    CHOICE_GENDER = (
        ('М', 'мужчина'),
        ('Ж', 'женщина'),
    )

    name = models.CharField(max_length=255)
    age = models.PositiveIntegerField(default=18)
    city = models.CharField(max_length=255)
    gender = models.CharField(max_length=255, choices=CHOICE_GENDER, default=CHOICE_GENDER[1][0])
    bio = models.TextField()
    photo = models.ImageField(upload_to='users/', default='users/default_avatar.jpg')

    likes = models.ManyToManyField('self', blank=True, symmetrical=False, related_name='liked_users')
    dislikes = models.ManyToManyField('self', blank=True, symmetrical=False, related_name='disliked_users')

    user_permissions = models.ManyToManyField(
        Permission,
        verbose_name='user permissions',
        blank=True,
    )

    groups = models.ManyToManyField(
        'auth.Group',
        verbose_name='groups',
        blank=True,
        help_text='Группы, к которым принадлежит этот пользователь.',
    )

    def __str__(self):
        return f'Имя - {self.name}, Логин - {self.username}, пол - {self.gender}, возраст - {self.age}, город - {self.city}'

matching/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic import ListView
from accounts.models import User


class SearchPairListView(ListView):
    model = User
    template_name = 'matching/search_pair.html'
    context_object_name = 'random_user'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        current_user = self.request.user
        opposite_gender = 'М' if current_user.gender == 'Ж' else 'Ж'
        context['random_user'] = User.objects.filter(
            gender=opposite_gender).exclude(id=current_user.id).order_by('?').first()
        return context


class LikeUserView(View):
    def post(self, request, user_id):
        user_to_like = get_object_or_404(User, id=user_id)
        current_user = request.user
        current_user.likes.add(user_to_like)
        return redirect('matching:search_pair')


class DislikeUserView(View):
    def post(self, request, user_id):
        user_to_dislike = get_object_or_404(User, id=user_id)
        current_user = request.user
        current_user.dislikes.add(user_to_dislike)
        return redirect('matching:search_pair')

matching/templates/matching/search_pair.html
{% extends 'core/template_site.html' %}

{% block title %}Поиск пары{% endblock %}

{% block content %}
<div style="max-width: 400px;">
    {% if random_user %}
    <div class="buttons-container-match">
        <form action="{% url 'matching:like' random_user.id %}" method="post">
            {% csrf_token %}
            <button class="like" type="submit">Нравится</button>
        </form>

        <form method="POST" action="{% url 'matching:dislike' random_user.id %}">
            {% csrf_token %}
            <button class="dislike" type="submit">Не нравится</button>
        </form>
    </div>
    <div class="pair-profile-match">
        <div class="avatar">
            <img src="{{ random_user.photo.url }}" alt="Аватар" class="profile-image-style">
        </div>
        <div class="profile-field-match">
            <p>Имя: {{ random_user.name }}</p>
            <p>Возраст: {{ random_user.age }}</p>
            <p>Город: {{ random_user.city }}</p>
            <p>Пол: {{ random_user.get_gender_display }}</p>
            <p>О себе: {{ random_user.bio }}</p>
        </div>
    </div>
    {% else %}
    <p class="or-text" style="font-size: 24px;">Пользователи не найдены!</p>
    {% endif %}
</div>
{% endblock %}