accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.RegisterFormView.as_view(), name='register'),
    path('login/', views.LoginFormView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('delete/', views.DeleteAccountView.as_view(), name='delete'),
    path('cancel-delete/', views.cancel_delete, name='cancel_delete'),
    path('profile/update/', views.ProfileUpdateView.as_view(), name='update'),
]

core/urls.py
from django.urls import path
from . import views
from .views import ProfileView
from django.conf import settings
from django.conf.urls.static import static

app_name = 'core'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('profile/', ProfileView.as_view(), name='profile'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

matching/urls.py
from django.urls import path
from . import views

app_name = 'matching'

urlpatterns = [
    path('search_pair/', views.SearchPairListView.as_view(), name='search_pair'),
    path('like/<int:user_id>/', views.LikeUserView.as_view(), name='like'),
    path('dislike/<int:user_id>/', views.DislikeUserView.as_view(), name='dislike'),
]

messaging/urls.py
from django.urls import path
from .views import DialogListView, DialogDetailView, MessageCreateView

app_name = 'messaging'

urlpatterns = [
    path('', DialogListView.as_view(), name='dialog_list'),
    path('dialog/<int:dialog_id>/', DialogDetailView.as_view(), name='dialog_detail'),
    path('dialog/<int:dialog_id>/message/create/', MessageCreateView.as_view(), name='message_create'),
]

project_laska/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
    path('stories/', include('stories.urls')),
    path('matching/', include('matching.urls')),
    path('messages/', include('messaging.urls', namespace='messaging')),
]

stories/urls.py
from django.urls import path
from . import views

app_name = 'stories'

urlpatterns = [
    path('', views.StoryListView.as_view(), name='story_list'),
    path('add/', views.AddStoryView.as_view(), name='add'),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, DetailView
from accounts.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.


class Index(TemplateView):
    template_name = 'core/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        return context


class ProfileView(TemplateView):
    template_name = 'core/profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        return context

core/templates/core/index.html
{% extends 'core/template_site.html'%}

{% block title %}Сайт знакомств{% endblock %}


{% block content %}

{% if user.is_authenticated %}



<div class="profile-field">
		<p style="font-size: 22px; text-align:center; width: 400px;">
			Добро пожаловать, {{ user.username }}!<br>
		</p>
		<p style="font-size: 22px; text-align:justify; width: 400px;">
			Найдите новые знакомства и общайтесь с интересными людьми.
		</p>

	</div>
</div>

{% else %}

<div class="buttons-container">
	<form action="{% url 'accounts:register' %}" method="post">
		{% csrf_token %}
		<button type="submit">Зарегистрироваться</button>
	</form>
	<h3 class="or-text">или</h3>
	<form action="{% url 'accounts:login' %}" method="post">
		{% csrf_token %}
		<button type="submit">Войти</button>
	</form>
</div>

{% endif %}

{% endblock %}

core/templates/core/profile.html
{% extends 'core/template_site.html' %}

{% block content %}
<div style="max-height: 500px; margin-top: -200px;">
    <div class='profile-field'>
        <img src="{{ user.photo.url }}" alt="Фото профиля" class="profile-image-style">
        <p>Имя: {{ user.name }}</p>
        <p>Логин: {{ user.username }}</p>
        <p>Пол: {{ user.gender }}</p>
        <p>Возраст: {{ user.age }}</p>
        <p>Город: {{ user.city }}</p>
        <p>О себе: {{ user.bio }}</p>

        <a href="{% url 'accounts:update' %}">Редактировать профиль</a>
        <a href="{% url 'accounts:logout' %}">Выйти</a>
        <a class="delete-profile" href="{% url 'accounts:delete' %}">Удалить профиль</a>
    </div>
</div>
{% endblock %}

core/templates/core/template_site.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">

<head>
	<meta charset="UTF-8">
	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'core/css/style.css' %}">
</head>

<body>
	
	{% if not user.is_authenticated %}
	<div class="logo">
		<img src="/static/core/media/logo_name2.png">
	</div>
	{% else %}
	<div class="header">
		<div class="menu">
			<a href="{% url 'stories:story_list' %}" >Истории</a>
			<a href="{% url 'matching:search_pair' %}">Поиск пары</a>
		</div>
		<div class="logo-menu">
			<img src="/static/core/media/logo_name2.png">
		</div>
		<div class="menu">
			<a href="{% url 'core:profile' %}">Мой профиль</a>
			<a href="{% url 'messaging:dialog_list' %}">Сообщения</a>
		</div>
	</div>
	{% endif %}

	{% block content %}

	{% endblock %}
</body>

</html>