core/urls.py
from django.urls import path
from . import views
from .views import ProfileView
from django.conf import settings
from django.conf.urls.static import static

app_name = 'core'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('profile/', ProfileView.as_view(), name='profile'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

messaging/urls.py
from django.urls import path
from .views import DialogListView, DialogDetailView, MessageCreateView

app_name = 'messaging'

urlpatterns = [
    path('', DialogListView.as_view(), name='dialog_list'),
    path('dialog/<int:dialog_id>/', DialogDetailView.as_view(), name='dialog_detail'),
    path('dialog/<int:dialog_id>/message/create/', MessageCreateView.as_view(), name='message_create'),
]

project_laska/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
    path('stories/', include('stories.urls')),
    path('matching/', include('matching.urls')),
    path('messages/', include('messaging.urls', namespace='messaging')),
]

messaging/models.py
from django.db import models
from accounts.models import User

class Dialog(models.Model):
    user1 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='dialogs1')
    user2 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='dialogs2')

    def __str__(self):
        return f"{self.user1.username} - {self.user2.username}"

    @classmethod
    def create_dialog(cls, user1, user2):
        if cls.objects.filter(user1=user2, user2=user1).exists():
            return cls.objects.filter(user1=user2, user2=user1).first()
        
        if user1.likes.filter(id=user2.id).exists() and user2.likes.filter(id=user1.id).exists():
            dialog = cls(user1=user1, user2=user2)
            dialog.save()
            return dialog
        
        return None
    
class Message(models.Model):
    dialog = models.ForeignKey(Dialog, on_delete=models.CASCADE)
    sender = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

messaging/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from .models import Dialog, Message

class DialogListView(View):
    def get(self, request):
        user = request.user
        dialogs = Dialog.objects.filter(user1=user) | Dialog.objects.filter(user2=user)

        matches = user.likes.filter(liked_users=user)

        existing_dialogs = dialogs.values_list('user1_id', 'user2_id')

        # Формируем список новых диалогов, которых еще нет у пользователя
        new_dialogs = []
        for match in matches:
            if (user.id, match.id) not in existing_dialogs and (match.id, user.id) not in existing_dialogs:
                dialog = Dialog.create_dialog(user, match)
                if dialog is not None:
                    new_dialogs.append(dialog)

        dialogs |= Dialog.objects.filter(id__in=[dialog.id for dialog in new_dialogs])

        return render(request, 'messaging/dialog_list.html', {'dialogs': dialogs})


class DialogDetailView(View):
    def get(self, request, dialog_id):
        dialog = get_object_or_404(Dialog, id=dialog_id)
        messages = dialog.message_set.order_by('created_at') 
        return render(request, 'messaging/dialog_detail.html', {'dialog': dialog, 'messages': messages})

class MessageCreateView(View):
    def post(self, request, dialog_id):
        dialog = get_object_or_404(Dialog, id=dialog_id)
        content = request.POST.get('content')
        sender = request.user
        message = Message(dialog=dialog, sender=sender, content=content)
        message.save()
        return redirect('messaging:dialog_detail', dialog_id=dialog_id)

messaging/templates/messaging/dialog_detail.html
{% extends 'core/template_site.html' %}

{% block title %}Сообщения{% endblock %}

{% block content %}
<h2 class="list-dialog">
	<img src="{{ dialog.user2.photo.url }}" alt="User Photo" width="40" height="40">
	{{ dialog.user2.name }}
</h2>

{% for message in messages %}
    <p class="button-dialog" style="margin:0; font-family: Georgia; width: 400px; ">{{ message.sender.name }}: {{ message.content }}</p>
{% empty %}
    <p>Нет сообщений!</p>
{% endfor %}


<form method="post" action="{% url 'messaging:message_create' dialog_id=dialog.id %}">
	{% csrf_token %}
	<input class="input-dialog" type="text" name="content" placeholder="Введите сообщение" required>
	<button class="button-dialog" type="submit">&ensp;⬆&ensp;</button>
</form>
{% endblock %}

messaging/templates/messaging/dialog_list.html
{% extends 'core/template_site.html' %}

{% block title %}Сообщения{% endblock %}

{% block content %}
    {% for dialog in dialogs %}
        <a class="list-dialog" href="{% url 'messaging:dialog_detail' dialog_id=dialog.id %}">
            {% if dialog.user1 == user %}
                <img src="{{ dialog.user2.photo.url }}" alt="User Photo" width="40" height="40">
                {{ dialog.user2.name }}
            {% else %}
                <img src="{{ dialog.user1.photo.url }}" alt="User Photo" width="40" height="40">
                {{ dialog.user1.name }}
            {% endif %}
        </a>
    {% empty %}
        <p class="or-text">Нет диалогов!</p>
    {% endfor %}
{% endblock %}