core/urls.py
from django.urls import path
from . import views
from .views import ProfileView
from django.conf import settings
from django.conf.urls.static import static

app_name = 'core'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('profile/', ProfileView.as_view(), name='profile'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project_laska/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
    path('stories/', include('stories.urls')),
    path('matching/', include('matching.urls')),
    path('messages/', include('messaging.urls', namespace='messaging')),
]

stories/urls.py
from django.urls import path
from . import views

app_name = 'stories'

urlpatterns = [
    path('', views.StoryListView.as_view(), name='story_list'),
    path('add/', views.AddStoryView.as_view(), name='add'),
]

stories/models.py
from django.db import models
from accounts.models import User

class Story(models.Model):
    topic = models.CharField(max_length=255)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.topic

stories/forms.py
from django import forms
from .models import Story

class StoryForm(forms.ModelForm):
    class Meta:
        model = Story
        fields = ['topic', 'content']

stories/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, CreateView
from .models import Story
from .forms import StoryForm
from django.urls import reverse_lazy


class StoryListView(ListView):
    model = Story
    template_name = 'stories/story_list.html'
    context_object_name = 'stories'
    ordering = ['-created_at']

    def get_queryset(self):
        queryset = super().get_queryset()
        search_query = self.request.GET.get('search')
        if search_query:
            queryset = queryset.filter(topic__iregex=search_query)
        return queryset


class AddStoryView(CreateView):
    model = Story
    form_class = StoryForm
    template_name = 'stories/add_story.html'
    success_url = reverse_lazy('stories:story_list')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

stories/templates/stories/add_story.html
{% extends 'core/template_site.html' %}

{% block title %}Добавить историю{% endblock %}

{% block content %}
<div class="form-container">
	<form method="post">
		{% csrf_token %}
		<label for="topic">Тема:</label>
		<input type="text" id="topic" name="topic" required>
		<label for="content">Содержание:</label>
		<textarea class="custom-textarea" id="content" name="content" required></textarea>
		<button type="submit">Добавить историю</button>
	</form>
</div>
{% endblock %}

stories/templates/stories/story_list.html
{% extends 'core/template_site.html' %}

{% block title %}Истории{% endblock %}

{% block content %}
<div>
	<div class="story-controls">
		<form method="GET">
			<input type="text" id="search" name="search" placeholder="Поиск по теме" value="{{ request.GET.search }}">
			<button type="submit">Поиск</button>
		</form>
		<div>
			<a href="{% url 'stories:add' %}">Добавить историю</a>
		</div>
	</div>

	<div style="max-height: 85vh;">
		{% for story in stories %}
		<div class="story">
			<p class="topic-story">{{ story.topic }}</p>
			<p>{{ story.content }}</p>
		</div>
		{% empty %}
		<p class="or-text" style="font-size: 24px;">Нет доступных историй.</p>
		{% endfor %}
	</div>
</div>
{% endblock %}